cmake_minimum_required(VERSION 3.5)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)

if(NOT QV_QT_LIBNAME)
    set(QV_QT_LIBNAME Qt6)
endif()

find_package(${QV_QT_LIBNAME} COMPONENTS Gui Widgets)

set(QVGUIPLUGIN_INTERFACE_HEADERS
    ${QVPLUGIN_INTERFACE_INCLUDE_DIR}/QvGUIPluginInterface.hpp)

list(APPEND QV2RAY_QT_LIBS ${QV_QT_LIBNAME}::Gui ${QV_QT_LIBNAME}::Widgets)
